fixtures:
  forge_modules:
    apache: "puppetlabs/apache"
    mysql: "puppetlabs/mysql"
    memcached: "saz/memcached"
    stdlib: "puppetlabs/stdlib"
    firewall: "puppetlabs/firewall"
    concat: "puppetlabs/concat"
  symlinks:
    mediawiki: "#{source_dir}"
